{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.120.963.0 (23.08)"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"avansData Contoso_Calendar\",\"avansData Contoso_Channel\",\"avansData Contoso_Product\",\"avansData Contoso_Geography\",\"avansData Contoso_Product_Category\",\"avansData Contoso_ProductSubcategory\",\"avansData Contoso_Promotion\",\"avansData Contoso_Sales\",\"avansData Contoso_Stores\",\"avansData Gross National Income Per Capita\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "75b19fd8-61dd-4f46-8bff-124d7a83a21b",
        "fromColumn": "ProductKey",
        "fromTable": "avansData Contoso_Sales",
        "toColumn": "ProductKey",
        "toTable": "avansData Contoso_Product"
      },
      {
        "name": "f0360018-7fa4-44c0-b529-a4a325eb1c98",
        "fromColumn": "ProductSubcategoryKey",
        "fromTable": "avansData Contoso_Product",
        "toColumn": "ProductSubcategoryKey",
        "toTable": "avansData Contoso_ProductSubcategory"
      },
      {
        "name": "f1c59ee2-55ea-4b78-9172-81d9282daf45",
        "fromColumn": "GeographyKey",
        "fromTable": "avansData Contoso_Stores",
        "toColumn": "GeographyKey",
        "toTable": "avansData Contoso_Geography"
      },
      {
        "name": "4792e2de-5aac-40fe-895c-a375f0eb4015",
        "fromColumn": "ProductCategoryKey",
        "fromTable": "avansData Contoso_ProductSubcategory",
        "toColumn": "ProductCategoryKey",
        "toTable": "avansData Contoso_Product_Category"
      },
      {
        "name": "2ace458b-691a-4574-92a1-ca73930e8d4e",
        "fromColumn": "PromotionKey",
        "fromTable": "avansData Contoso_Sales",
        "toColumn": "PromotionKey",
        "toTable": "avansData Contoso_Promotion"
      },
      {
        "name": "dd165123-3f2c-4485-b006-d5970532281b",
        "fromColumn": "StoreKey",
        "fromTable": "avansData Contoso_Sales",
        "toColumn": "StoreKey",
        "toTable": "avansData Contoso_Stores"
      },
      {
        "name": "18147a73-d010-4de1-a2b9-8dd1d475fe28",
        "fromColumn": "channelKey",
        "fromTable": "avansData Contoso_Sales",
        "toColumn": "Channel",
        "toTable": "avansData Contoso_Channel"
      },
      {
        "name": "1820e296-6044-4459-bd0e-20ed138d3459",
        "fromColumn": "DateKey",
        "fromTable": "avansData Contoso_Sales",
        "toColumn": "DateInt",
        "toTable": "avansData Contoso_Calendar"
      }
    ],
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "avansData Contoso_Calendar",
        "columns": [
          {
            "name": "DateInt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2733187c-01c4-43d0-9876-acf588640dad",
            "sourceColumn": "DateInt",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "eb41068a-13b0-481a-8176-8e385778e4ad",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58d61698-e8fa-414a-af26-053260243298",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ed7412f8-9640-4c10-8ff0-6cb9a53ea003",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "ee03876a-ea5d-4d00-9861-dfe916248440",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "DayOfMonth",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "274387ee-9dc0-4d71-b36e-0ee69550ef37",
            "sourceColumn": "DayOfMonth",
            "summarizeBy": "none"
          },
          {
            "name": "DayOfWeekName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f86b495f-820d-4673-ad0f-8eb1077e5040",
            "sourceColumn": "DayOfWeekName",
            "summarizeBy": "none"
          },
          {
            "name": "MonthName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5913f8e4-f676-44cd-8fe4-0dbec04e5129",
            "sourceColumn": "MonthName",
            "summarizeBy": "none"
          },
          {
            "name": "MonthOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7e4e44ce-ff74-4761-acf0-7ae6c2f1cdc2",
            "sourceColumn": "MonthOfYear",
            "summarizeBy": "none"
          },
          {
            "name": "QuarterOfYear",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4f23d15e-db58-4f5d-a630-ebb943662d56",
            "sourceColumn": "QuarterOfYear",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8ec8d295-d688-4dbf-92ce-fa0c17aa047c",
        "partitions": [
          {
            "name": "avansData Contoso_Calendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"161.97.97.200\", \"avansData\"),",
                "    avansData_Contoso_Calendar = Source{[Schema=\"avansData\",Item=\"Contoso_Calendar\"]}[Data]",
                "in",
                "    avansData_Contoso_Calendar"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_eebeb993-38de-470f-af85-56049ddadf93",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cfc8b188-bf56-49e8-bb46-9f7a21540b51",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "143d5a63-5dc1-4627-b3b5-1d0f3056cd48",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "6755b786-1298-4c55-967a-94efb3a19eff",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ac01a1fd-1dcf-4e83-9cb7-5a1e6d047ffd",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "14572c7d-b38f-4149-b1e1-029738ec0eed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "ada6a6c4-9a73-480f-9545-300d1bd1259b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "lineageTag": "251c3541-c863-48de-9659-c53b8a4f5208",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "b28fe2b1-84a6-474c-bacc-27d0d3c28b5e",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d39287ac-4b10-43d1-a7ea-e39ca8dc3210",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "53247128-5508-4f53-8266-2e59bef3e4ac",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "338caecd-2afb-417d-a143-22380060a87d",
                "ordinal": 3
              }
            ],
            "lineageTag": "4119e28c-6833-40fa-97a1-9a031316aafa"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "9d7a2ad7-d80c-439c-87a7-1e3b3f64cbb5",
        "partitions": [
          {
            "name": "DateTableTemplate_eebeb993-38de-470f-af85-56049ddadf93",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "avansData Contoso_Channel",
        "columns": [
          {
            "name": "Channel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b83f43d4-1624-4a1e-b495-d147d88835bb",
            "sourceColumn": "Channel",
            "summarizeBy": "none"
          },
          {
            "name": "ChannelName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba45d744-4d25-4fa0-ad85-ce692be7ea63",
            "sourceColumn": "ChannelName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9e338bab-71b5-4b85-89d0-4c89dddba61c",
        "partitions": [
          {
            "name": "avansData Contoso_Channel",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"161.97.97.200\", \"avansData\"),",
                "    avansData_Contoso_Channel = Source{[Schema=\"avansData\",Item=\"Contoso_Channel\"]}[Data]",
                "in",
                "    avansData_Contoso_Channel"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "avansData Contoso_Product",
        "columns": [
          {
            "name": "BrandName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "097839f6-f386-41a9-82d6-3b8927df64fa",
            "sourceColumn": "BrandName",
            "summarizeBy": "none"
          },
          {
            "name": "ClassName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bf8752aa-2b08-4092-8866-f8ee4249d9a2",
            "sourceColumn": "ClassName",
            "summarizeBy": "none"
          },
          {
            "name": "Manufacturer",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dd7300a8-b333-4307-93b2-d2ff963654d3",
            "sourceColumn": "Manufacturer",
            "summarizeBy": "none"
          },
          {
            "name": "ProductDescription",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96aee8c7-20d8-40c1-b4cd-0297a9899707",
            "sourceColumn": "ProductDescription",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d07992c4-478c-4b05-875e-ba95f41de7c9",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f33072c-03ff-4eb0-887b-4f1e6aeae8ca",
            "sourceColumn": "ProductName",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3b4be8fe-999a-4716-b41a-34f11c4018ea",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "UnitCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd49e247-0c97-4164-9704-9d27c1733cce",
            "sourceColumn": "UnitCost",
            "summarizeBy": "none"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad425b2c-71b9-4989-b191-8bf05f8eb04a",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e7299768-0dca-4937-82ab-d504d639a78d",
        "partitions": [
          {
            "name": "avansData Contoso_Product",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"161.97.97.200\", \"avansData\"),",
                "    avansData_Contoso_Product = Source{[Schema=\"avansData\",Item=\"Contoso_Product\"]}[Data]",
                "in",
                "    avansData_Contoso_Product"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "avansData Contoso_Geography",
        "columns": [
          {
            "name": "ContinentName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41102b79-7a88-432e-acf8-73af8ff5cd03",
            "sourceColumn": "ContinentName",
            "summarizeBy": "none"
          },
          {
            "name": "GeographyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9e16f637-d5b4-45b5-be51-47266d3ba1ad",
            "sourceColumn": "GeographyKey",
            "summarizeBy": "none"
          },
          {
            "name": "GeographyType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb6a00f3-3706-4e22-9d0b-382bd32174b8",
            "sourceColumn": "GeographyType",
            "summarizeBy": "none"
          },
          {
            "name": "RegionCountryName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ca72f42-48ad-4f99-a0e4-6dc29abd98e9",
            "sourceColumn": "RegionCountryName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8730a8b8-7129-45ef-9e9d-1b29205341f8",
        "partitions": [
          {
            "name": "avansData Contoso_Geography",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"161.97.97.200\", \"avansData\"),",
                "    avansData_Contoso_Geography = Source{[Schema=\"avansData\",Item=\"Contoso_Geography\"]}[Data]",
                "in",
                "    avansData_Contoso_Geography"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "avansData Contoso_Product_Category",
        "columns": [
          {
            "name": "ProductCategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8fb3e746-3326-40c9-b6f5-527b30520d74",
            "sourceColumn": "ProductCategory",
            "summarizeBy": "none"
          },
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "efab53d8-127f-4b67-b93a-4a04c6af063b",
            "sourceColumn": "ProductCategoryKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "efb5edc5-b4c1-4546-88e2-3ed3b508c562",
        "partitions": [
          {
            "name": "avansData Contoso_Product_Category",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"161.97.97.200\", \"avansData\"),",
                "    avansData_Contoso_Product_Category = Source{[Schema=\"avansData\",Item=\"Contoso_Product_Category\"]}[Data]",
                "in",
                "    avansData_Contoso_Product_Category"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "avansData Contoso_ProductSubcategory",
        "columns": [
          {
            "name": "ProductCategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e3fff286-5454-470b-86a2-43a8e594d247",
            "sourceColumn": "ProductCategoryKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSubcategory",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f20e3da2-94ab-4677-83c7-2d2bff657960",
            "sourceColumn": "ProductSubcategory",
            "summarizeBy": "none"
          },
          {
            "name": "ProductSubcategoryKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "aac744c5-8567-4a86-958a-aa260191fe71",
            "sourceColumn": "ProductSubcategoryKey",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "fdda2a07-9e83-4de4-947f-eac4fb00c0a2",
        "partitions": [
          {
            "name": "avansData Contoso_ProductSubcategory",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"161.97.97.200\", \"avansData\"),",
                "    avansData_Contoso_ProductSubcategory = Source{[Schema=\"avansData\",Item=\"Contoso_ProductSubcategory\"]}[Data]",
                "in",
                "    avansData_Contoso_ProductSubcategory"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "avansData Contoso_Promotion",
        "columns": [
          {
            "name": "DiscountPercent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "19bab095-20bd-4a3f-80ae-a7ca76607715",
            "sourceColumn": "DiscountPercent",
            "summarizeBy": "none"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "973e8578-87e6-4e0c-aa0f-04156ca8c204",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "794dd1f6-cf1f-404d-ade4-88c9f871d109",
            "sourceColumn": "Quarter",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "789f9cd8-7ac6-420e-8d80-c6233b608b1b",
            "sourceColumn": "Month",
            "summarizeBy": "none"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "3b5c1886-b4f3-42cb-a7ac-f0f3f8698703",
            "sourceColumn": "Day",
            "summarizeBy": "none"
          },
          {
            "name": "PromotionKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "123613c9-e820-4e68-93cc-342a3d17f782",
            "sourceColumn": "PromotionKey",
            "summarizeBy": "none"
          },
          {
            "name": "PromotionLabel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "53908866-c770-4611-b135-f7d5b17d6e7b",
            "sourceColumn": "PromotionLabel",
            "summarizeBy": "none"
          },
          {
            "name": "PromotionName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "edcf4e6a-1028-4486-b3e9-dc325cf315e2",
            "sourceColumn": "PromotionName",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b9d3af76-b21c-4586-ac42-ad3dc66c7438",
        "partitions": [
          {
            "name": "avansData Contoso_Promotion",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"161.97.97.200\", \"avansData\"),",
                "    avansData_Contoso_Promotion = Source{[Schema=\"avansData\",Item=\"Contoso_Promotion\"]}[Data]",
                "in",
                "    avansData_Contoso_Promotion"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "avansData Contoso_Sales",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "SalesKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4e1e4deb-c932-4b3e-a029-52ce0ddf9817",
            "sourceColumn": "SalesKey",
            "summarizeBy": "count"
          },
          {
            "name": "DateKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "473b0f03-1449-4ec4-bb76-b080386b4cf6",
            "sourceColumn": "DateKey",
            "summarizeBy": "none"
          },
          {
            "name": "channelKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a1abb2a2-81bd-494d-9e8c-8774e0dda733",
            "sourceColumn": "channelKey",
            "summarizeBy": "none"
          },
          {
            "name": "StoreKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5f0f4359-97ce-4cc6-987e-53ba28d4b163",
            "sourceColumn": "StoreKey",
            "summarizeBy": "none"
          },
          {
            "name": "ProductKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "456a6378-f289-4ef9-a2e2-f8e73c1fd119",
            "sourceColumn": "ProductKey",
            "summarizeBy": "none"
          },
          {
            "name": "PromotionKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5c83afdf-04e2-4e7e-8f66-427759c8b5b8",
            "sourceColumn": "PromotionKey",
            "summarizeBy": "none"
          },
          {
            "name": "UnitCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2fee091a-e8a1-4cf2-876a-ac1be8bbb083",
            "sourceColumn": "UnitCost",
            "summarizeBy": "none"
          },
          {
            "name": "UnitPrice",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e4c0c193-22c7-494b-aa70-e0871313dfa0",
            "sourceColumn": "UnitPrice",
            "summarizeBy": "none"
          },
          {
            "name": "SalesQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "86f4999f-81f6-4fdc-aaff-0c5678b3ba2a",
            "sourceColumn": "SalesQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "ReturnQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1f7b5fc1-30b9-4e83-9804-6a95ddf26f12",
            "sourceColumn": "ReturnQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "ReturnAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1212ef0b-acfd-4b91-99b7-26feee203e19",
            "sourceColumn": "ReturnAmount",
            "summarizeBy": "none"
          },
          {
            "name": "DiscountQuantity",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "223e35d3-fc62-4ed9-ba12-159a5458fe41",
            "sourceColumn": "DiscountQuantity",
            "summarizeBy": "sum"
          },
          {
            "name": "DiscountAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f512891c-a8e6-4562-9602-7a6e3fb6243a",
            "sourceColumn": "DiscountAmount",
            "summarizeBy": "none"
          },
          {
            "name": "TotalCost",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0af10866-7144-4905-8221-868c49d5c4e7",
            "sourceColumn": "TotalCost",
            "summarizeBy": "none"
          },
          {
            "name": "SalesAmount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8d7c1935-b3a0-492a-8dcd-5b8280269655",
            "sourceColumn": "SalesAmount",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f4edda52-2231-49b6-89ea-05c53422b0e9",
        "partitions": [
          {
            "name": "avansData Contoso_Sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"161.97.97.200\", \"avansData\"),",
                "    avansData_Contoso_Sales = Source{[Schema=\"avansData\",Item=\"Contoso_Sales\"]}[Data],",
                "    #\"Replaced Value\" = Table.ReplaceValue(avansData_Contoso_Sales,\" 00:00:00,000\",\"\",Replacer.ReplaceText,{\"DateKey\"}),",
                "    #\"Replaced Value1\" = Table.ReplaceValue(#\"Replaced Value\",\"-\",\"\",Replacer.ReplaceText,{\"DateKey\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Replaced Value1\",{{\"DateKey\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "avansData Contoso_Stores",
        "columns": [
          {
            "name": "CloseReason",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a26d0e11-f78e-4fe3-836f-34e238884602",
            "sourceColumn": "CloseReason",
            "summarizeBy": "none"
          },
          {
            "name": "EmployeeCount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "4ccb6d67-c63a-43f5-8a15-386867d1bb83",
            "sourceColumn": "EmployeeCount",
            "summarizeBy": "sum"
          },
          {
            "name": "GeographyKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e412cbb1-276c-4003-a05b-9049753fba5f",
            "sourceColumn": "GeographyKey",
            "summarizeBy": "none"
          },
          {
            "name": "SellingAreaSize",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "65ecd2f6-f34f-409e-92fa-13cb810a5932",
            "sourceColumn": "SellingAreaSize",
            "summarizeBy": "sum"
          },
          {
            "name": "Status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30f080aa-2c50-474c-9db4-11d29702de41",
            "sourceColumn": "Status",
            "summarizeBy": "none"
          },
          {
            "name": "StoreKey",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "58e7d972-6119-4df6-aa8a-52d6b1905abf",
            "sourceColumn": "StoreKey",
            "summarizeBy": "none"
          },
          {
            "name": "StoreName",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "51b449f5-7c2b-482c-b350-7b221354bc4a",
            "sourceColumn": "StoreName",
            "summarizeBy": "none"
          },
          {
            "name": "StoreType",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0c459be-50f5-4bf6-a326-77718297ef6b",
            "sourceColumn": "StoreType",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3b33fa4b-4f8e-4fe8-b42d-d44a1891b348",
        "partitions": [
          {
            "name": "avansData Contoso_Stores",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"161.97.97.200\", \"avansData\"),",
                "    avansData_Contoso_Stores = Source{[Schema=\"avansData\",Item=\"Contoso_Stores\"]}[Data]",
                "in",
                "    avansData_Contoso_Stores"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "avansData Gross National Income Per Capita",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "iso3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "597a15bc-9636-4429-b79a-a18bdd80d8b4",
            "sourceColumn": "iso3",
            "summarizeBy": "none"
          },
          {
            "name": "Country",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a0bebcb-957d-40d2-8f53-5d131c1e08a2",
            "sourceColumn": "Country",
            "summarizeBy": "none"
          },
          {
            "name": "Continent",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "77f56ba6-203d-4a74-9043-86781b2ccaad",
            "sourceColumn": "Continent",
            "summarizeBy": "none"
          },
          {
            "name": "Hemisphere",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e1a84b31-a906-48b4-8793-ac91c20f9bb9",
            "sourceColumn": "Hemisphere",
            "summarizeBy": "none"
          },
          {
            "name": "Human Development Groups",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4dc44ff9-dc20-4dd7-8c0b-9f8445c8b040",
            "sourceColumn": "Human Development Groups",
            "summarizeBy": "none"
          },
          {
            "name": "UNDP Developing Regions",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "369008d0-d02b-4372-a45e-0769a5497901",
            "sourceColumn": "UNDP Developing Regions",
            "summarizeBy": "none"
          },
          {
            "name": "HDI Rank (2021)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "00a5d1ba-5cfb-4eb3-a9f9-1304425319d6",
            "sourceColumn": "HDI Rank (2021)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (1990)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1825d12f-cdc2-41f6-b5f5-155691b51889",
            "sourceColumn": "Gross National Income Per Capita (1990)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (1991)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ed357d13-2e35-47cf-a9a4-d434d9abf243",
            "sourceColumn": "Gross National Income Per Capita (1991)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (1992)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1856f365-7b84-4ee8-aaca-666a33f2abb4",
            "sourceColumn": "Gross National Income Per Capita (1992)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (1993)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "68ac023f-77ae-49f6-af09-b86f4110596e",
            "sourceColumn": "Gross National Income Per Capita (1993)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (1994)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0fd985d7-b56d-4a3c-8bdb-cd5525df6aab",
            "sourceColumn": "Gross National Income Per Capita (1994)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (1995)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bd044651-49eb-4bb3-917c-195caad61b78",
            "sourceColumn": "Gross National Income Per Capita (1995)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (1996)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f15d436f-8d7a-4022-a968-9f73912da6f8",
            "sourceColumn": "Gross National Income Per Capita (1996)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (1997)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "571024aa-3bf9-46e3-a2bb-5263991833df",
            "sourceColumn": "Gross National Income Per Capita (1997)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (1998)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "01f2b5b3-bbd0-488c-a6fd-2c548821f16b",
            "sourceColumn": "Gross National Income Per Capita (1998)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (1999)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "300ef0dc-3413-4514-8f9a-6df04de8c7b8",
            "sourceColumn": "Gross National Income Per Capita (1999)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2000)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4b6d4668-015e-4609-8bb6-1f0e8e404a7c",
            "sourceColumn": "Gross National Income Per Capita (2000)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2001)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f6f2245d-b904-4980-a42a-31dd5ca3f44a",
            "sourceColumn": "Gross National Income Per Capita (2001)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2002)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "dd259338-1020-4e01-8b63-fe2b315c16c4",
            "sourceColumn": "Gross National Income Per Capita (2002)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2003)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a50015d2-96c2-407b-9176-5706c351d5c8",
            "sourceColumn": "Gross National Income Per Capita (2003)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2004)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "df3d74d0-5d38-40ec-96c3-de7dd416cf92",
            "sourceColumn": "Gross National Income Per Capita (2004)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2005)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "77287802-c929-43e8-af0a-b8f8eaf4ae6c",
            "sourceColumn": "Gross National Income Per Capita (2005)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2006)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "bf0e444a-45da-4c47-a721-0f8388da4e64",
            "sourceColumn": "Gross National Income Per Capita (2006)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2007)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "174130e1-47b0-4d6e-815d-318debf8a22c",
            "sourceColumn": "Gross National Income Per Capita (2007)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2008)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "79ee8a00-07a8-41d6-9759-54f6f0d5c423",
            "sourceColumn": "Gross National Income Per Capita (2008)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2009)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c16b3c37-bbe7-4d68-909d-22f88d58304f",
            "sourceColumn": "Gross National Income Per Capita (2009)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2010)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "97358b11-7759-4b47-8550-a677ef3a613c",
            "sourceColumn": "Gross National Income Per Capita (2010)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2011)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b320b140-f3e5-4e50-b8b3-4e81750f406c",
            "sourceColumn": "Gross National Income Per Capita (2011)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2012)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "4fdeb54c-119c-40e6-9b34-7b4c65bfb4ce",
            "sourceColumn": "Gross National Income Per Capita (2012)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2013)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b316ba27-3b95-4ffd-a077-ca7873d777ef",
            "sourceColumn": "Gross National Income Per Capita (2013)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2014)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "882ffafe-eeef-428a-870c-66fcf0bc186a",
            "sourceColumn": "Gross National Income Per Capita (2014)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2015)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "44193a73-8a53-4e2a-a8e2-ebc9ce4c41d6",
            "sourceColumn": "Gross National Income Per Capita (2015)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2016)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d9593baa-e9d1-4242-a932-1257d1ad8bcc",
            "sourceColumn": "Gross National Income Per Capita (2016)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2017)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7a42fab9-c3ff-45fc-b535-52160a089c51",
            "sourceColumn": "Gross National Income Per Capita (2017)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2018)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7a30a536-71ec-4c28-b2be-b4ba8c837f36",
            "sourceColumn": "Gross National Income Per Capita (2018)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2019)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c87744e7-f570-49f5-befa-66a748fc4d99",
            "sourceColumn": "Gross National Income Per Capita (2019)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2020)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "66773680-028b-4d9f-9ce1-695b8890d6f8",
            "sourceColumn": "Gross National Income Per Capita (2020)",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross National Income Per Capita (2021)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "783fed26-dd4c-4608-b6a5-089b6d144c05",
            "sourceColumn": "Gross National Income Per Capita (2021)",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "154565fd-332c-4ab6-b17f-f14f535fb9c4",
        "partitions": [
          {
            "name": "avansData Gross National Income Per Capita",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = PostgreSQL.Database(\"161.97.97.200\", \"avansData\"),",
                "    #\"avansData_Gross National Income Per Capita\" = Source{[Schema=\"avansData\",Item=\"Gross National Income Per Capita\"]}[Data]",
                "in",
                "    #\"avansData_Gross National Income Per Capita\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}